### ISSUE TITLE
[feedback] c00-diamonds

### ISSUE THREAD

**Issue by zdelrosario** [rolandcrosby/data-science-work#1]
|Item      |Grade |
|:---------|:-----|
|Effort    |S     |
|Observed  |S     |
|Supported |U, 1  |
|Styled    |S     |

Comments

[1] Support for each observation is not clear: Document your observations near the figure/table where the obs. was made, rather than summarizing them at the end.\0

**Comment by rolandcrosby** [comment]
Thanks for the feedback! I wasn't sure what to do about multiple plots -- thought the exercise solution code was all supposed to be in one named code block -- but I'll be sure to put my observations in line with each plot next time.
